####
# This Dockerfile is used in order to build a container that runs the application in JVM mode
#
# Before building the container image run:
#
# mvn clean compile package
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm -t spring/calculator-jvm .
#
# Then, run the container using:
#
# docker run -i --rm -p 8080:8080 -e FIRST=1 -e OPERATION=+ -e SECOND=2 spring/calculator-jvm
#
# If you want to include the debug port into your docker image
# you will have to expose the debug port (default 5005) like this :  EXPOSE 8080 5005
#
# Then, run the container using :
#
# docker run -i --rm -p 8080:8080 -e FIRST=1 -e OPERATION=+ -e SECOND=2 spring/calculator-jvm
#
#
###
FROM amazoncorretto:21-alpine-jdk

COPY --chown=185 target/*.jar /deployments/

EXPOSE 8080
USER 185

ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
#ENV JAVA_APP_JAR="/deployments/calculator-0.0.1-SNAPSHOT.jar"
ENV FIRST="1"
ENV OPERATION="+"
ENV SECOND="1"

CMD /usr/bin/java -jar -Dspring.profiles.active=default /deployments/calculator-0.0.1-SNAPSHOT.jar $FIRST $OPERATION $SECOND
